name: Run tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        BASE_URL: ${{ env.BASE_URL }}
      run: npm run test:headless:ci

    - name: Upload report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report/